apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oucb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-oucb@sha256:b3305e2fe41b1fbfd3a8e12bc267c4fcd33aca7753cd4fc45834c49abcca9eeb
        name: my-nodejs
        resources: {}
status: {}
